platform :ios, '10.0'
install! 'cocoapods',
disable_input_output_paths: true,
generate_multiple_pod_projects: true

use_frameworks!

target 'UIFlipView_Example' do
  pod 'UIFlipView', :path => '../'
end
